/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MWind;

import Copies.CopiesPlugins;
import Copies.CopiesViews;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ADRIAN COSTA
 */
public class MWindow extends javax.swing.JFrame {

    /**
     * Creates new form MWindow
     */
    public MWindow() {
        try {
            UIManager.LookAndFeelInfo looks[] = UIManager.getInstalledLookAndFeels();
            UIManager.setLookAndFeel(looks[1].getClassName());
        }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException | ArrayIndexOutOfBoundsException ex){}
        
    
    
    
        initComponents();
        
        Image IconI = Toolkit.getDefaultToolkit().createImage( this.getClass().getResource( "icon1.png" ) );
        this.setIconImage(IconI);
        this.setAlwaysOnTop( true );
        this.setResizable(false);
        this.setLocationRelativeTo( null );
        
        
        Views.ViewsIn = "D:\\COBIS_ALL\\AprendiendoDesigner\\build\\cobis\\web\\views\\TLLRS";
        plugins.pluginsIn = "D:\\COBIS_ALL\\AprendiendoDesigner\\build\\cobis";
        //
        Views.ViewsOut = "C:\\COBIS_HOME_WEB_MAP\\cwc\\webapps\\views";
        plugins.pluginsOut = "C:\\COBIS_HOME_WEB_MAP\\cwc\\plugins";
        this.setTitle( "Proyect Actions" );
        
    }
    
    
    class viewsParams{
        public String ViewsIn;
        public String ViewsOut;
    }
    
    
    class pluginsParams{
        public String pluginsIn;
        public String pluginsOut;
    }
    
    viewsParams   Views   = new viewsParams();
    pluginsParams plugins = new pluginsParams();

    
    String GetFolder( String defastr){
        String defastrT = defastr;
        if( defastrT==null ){
            defastrT = "";
        }
        JFileChooser chooser = new JFileChooser(); 
        chooser.setCurrentDirectory(new java.io.File(defastrT));
        chooser.setDialogTitle("Select folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            /*
            System.out.println("getCurrentDirectory(): " 
               +  chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : " 
               +  chooser.getSelectedFile());
            //*/
            return ""+chooser.getSelectedFile();
        }else{
            return defastr;
        }
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttViewsIn = new javax.swing.JButton();
        buttViewsOut = new javax.swing.JButton();
        labelFolderIn = new javax.swing.JLabel();
        labelFolderOut = new javax.swing.JLabel();
        buttViewsOut1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttPluginsIn = new javax.swing.JButton();
        buttPluginsOut = new javax.swing.JButton();
        labelFolderIn1 = new javax.swing.JLabel();
        labelFolderOut1 = new javax.swing.JLabel();
        CopyPlugins = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        GetPlan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        buttViewsIn.setText("Views IN");
        buttViewsIn.setPreferredSize(new java.awt.Dimension(83, 23));
        buttViewsIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttViewsInActionPerformed(evt);
            }
        });

        buttViewsOut.setText("Views OUT");
        buttViewsOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttViewsOutActionPerformed(evt);
            }
        });

        labelFolderIn.setText("C:\\");

            labelFolderOut.setText("C:\\");

                buttViewsOut1.setText("COPY Views");
                buttViewsOut1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        buttViewsOut1ActionPerformed(evt);
                    }
                });

                jLabel1.setText("VIEWs");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttViewsOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttViewsIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttViewsOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFolderIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelFolderOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttViewsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFolderIn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttViewsOut)
                            .addComponent(labelFolderOut))
                        .addGap(18, 18, 18)
                        .addComponent(buttViewsOut1)
                        .addContainerGap(24, Short.MAX_VALUE))
                );

                jPanel2.setBackground(new java.awt.Color(200, 200, 200));

                buttPluginsIn.setText("Plugins IN");
                buttPluginsIn.setPreferredSize(new java.awt.Dimension(83, 23));
                buttPluginsIn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        buttPluginsInActionPerformed(evt);
                    }
                });

                buttPluginsOut.setText("Plugins OUT");
                buttPluginsOut.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        buttPluginsOutActionPerformed(evt);
                    }
                });

                labelFolderIn1.setText("C:\\");

                    labelFolderOut1.setText("C:\\");

                        CopyPlugins.setText("COPY Plugins");
                        CopyPlugins.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CopyPluginsActionPerformed(evt);
                            }
                        });

                        jLabel2.setText("PLUGINs");

                        GetPlan.setText("Get Plan");
                        GetPlan.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                GetPlanActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                        jPanel2.setLayout(jPanel2Layout);
                        jPanel2Layout.setHorizontalGroup(
                            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(CopyPlugins, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GetPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(buttPluginsIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(buttPluginsOut))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelFolderIn1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                                            .addComponent(labelFolderOut1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))))
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                        );
                        jPanel2Layout.setVerticalGroup(
                            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttPluginsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFolderIn1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttPluginsOut)
                                    .addComponent(labelFolderOut1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(CopyPlugins)
                                        .addContainerGap(28, Short.MAX_VALUE))
                                    .addComponent(GetPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        );

                        jLabel3.setText("Creado por: Adrian Costa");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addContainerGap())
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void buttViewsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttViewsInActionPerformed
        // TODO add your handling code here:
        Views.ViewsIn = GetFolder(Views.ViewsIn);
        labelFolderIn.setText(Views.ViewsIn);
        JOptionPane.showMessageDialog( this, Views.ViewsIn, "Input of Views", JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_buttViewsInActionPerformed

    private void buttViewsOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttViewsOutActionPerformed
        // TODO add your handling code here:
        Views.ViewsOut = GetFolder(Views.ViewsOut);
        labelFolderOut.setText(Views.ViewsOut);
        JOptionPane.showMessageDialog( this, Views.ViewsOut, "Out of Views", JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_buttViewsOutActionPerformed

    private void buttViewsOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttViewsOut1ActionPerformed
        // TODO add your handling code here:
        if( CopiesViews.copies(Views.ViewsIn, Views.ViewsOut) ){
            JOptionPane.showMessageDialog( this, "Copy OK!!!.", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog( this, "Copy FAIL!!!.", "Failure", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttViewsOut1ActionPerformed

    private void buttPluginsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPluginsInActionPerformed
        // TODO add your handling code here:
        plugins.pluginsIn = GetFolder(plugins.pluginsIn);
        labelFolderIn1.setText(plugins.pluginsIn);
        JOptionPane.showMessageDialog( this, plugins.pluginsIn, "Input of plugins", JOptionPane.INFORMATION_MESSAGE );
    
    }//GEN-LAST:event_buttPluginsInActionPerformed

    private void buttPluginsOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPluginsOutActionPerformed
        // TODO add your handling code here:
        String str = GetFolder(plugins.pluginsOut);
        if( !str.toLowerCase().endsWith("cwc\\plugins") ){
            JOptionPane.showMessageDialog( this, "The path must end in:\n"+
                    "cwc\\plugins", 
                    "Failure", JOptionPane.ERROR_MESSAGE);
            return;
        }
        plugins.pluginsOut = str;
        labelFolderOut1.setText(plugins.pluginsOut);
        JOptionPane.showMessageDialog( this, plugins.pluginsOut, "Output of plugins", JOptionPane.INFORMATION_MESSAGE );
    
    }//GEN-LAST:event_buttPluginsOutActionPerformed
    
    String plan = "";
    CopiesPlugins cppl = new CopiesPlugins();
    private void CopyPluginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyPluginsActionPerformed
        
        plan = "";
        if( !cppl.copies( plugins.pluginsIn, plugins.pluginsOut) ){
            JOptionPane.showMessageDialog( this, "Fail!!!" );
            return;
        }
        plan = cppl.getplan();
        if( plan.isEmpty() ){
            JOptionPane.showMessageDialog( this, "No JARs found", "Failure", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog( this, plan, "PLAN", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CopyPluginsActionPerformed

    private void GetPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPlanActionPerformed
        // TODO add your handling code here:
        plan = cppl.getplan();
        if( plan.isEmpty() ){
            JOptionPane.showMessageDialog( this, "No JARs found", "Failure", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog( this, plan, "PLAN", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_GetPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CopyPlugins;
    private javax.swing.JButton GetPlan;
    private javax.swing.JButton buttPluginsIn;
    private javax.swing.JButton buttPluginsOut;
    private javax.swing.JButton buttViewsIn;
    private javax.swing.JButton buttViewsOut;
    private javax.swing.JButton buttViewsOut1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFolderIn;
    private javax.swing.JLabel labelFolderIn1;
    private javax.swing.JLabel labelFolderOut;
    private javax.swing.JLabel labelFolderOut1;
    // End of variables declaration//GEN-END:variables
}
